"""Event domain model.

An :class:`Event` is a single lifecycle notification emitted by the
agent - "this task started," "this task failed with exception X,"
"this worker went offline," and so on. Events are the raw stream
that feeds the brain's ``tasks``, ``workers``, ``queues``, and
``schedules`` tables.

High-volume table: partitioned by day, default retention 30 days.
See ``docs/DATABASE.md §3.8``.
"""

from __future__ import annotations

from datetime import datetime
from enum import StrEnum
from typing import Any
from uuid import UUID

from pydantic import Field

from z4j_core.models._base import Z4JModel


class EventKind(StrEnum):
    """Taxonomy of events z4j knows how to ingest.

    Every adapter maps its engine-native events onto this enumeration.
    Unknown events are accepted but mapped to ``UNKNOWN`` and flagged.
    """

    # Task lifecycle
    TASK_SENT = "task.sent"
    TASK_RECEIVED = "task.received"
    TASK_STARTED = "task.started"
    TASK_SUCCEEDED = "task.succeeded"
    TASK_FAILED = "task.failed"
    TASK_RETRIED = "task.retried"
    TASK_REVOKED = "task.revoked"
    TASK_REJECTED = "task.rejected"

    # Worker lifecycle
    WORKER_ONLINE = "worker.online"
    WORKER_OFFLINE = "worker.offline"
    WORKER_HEARTBEAT = "worker.heartbeat"

    # Queue reports
    QUEUE_DEPTH_REPORT = "queue.depth_report"

    # Schedule execution
    SCHEDULE_RUN_STARTED = "schedule.run_started"
    SCHEDULE_RUN_COMPLETED = "schedule.run_completed"

    # Schedule registry sync
    SCHEDULE_CREATED = "schedule.created"
    SCHEDULE_UPDATED = "schedule.updated"
    SCHEDULE_DELETED = "schedule.deleted"
    # Full inventory drop. Carries every schedule the agent's
    # adapter currently observes so the brain can reconcile
    # (insert new, update existing, soft-delete missing) in one
    # transaction. Emitted by the agent at boot, on a periodic
    # timer, and on demand via the ``schedule.resync`` command.
    # Event payload shape (in ``data``): ``{scheduler: str,
    # schedules: list[dict], reason: "boot"|"periodic"|"command"}``.
    # Added in 1.3.1 to close the "celery-beat schedules don't
    # show up until I edit them" gap. See docs/SCHEDULER.md §13.2.
    SCHEDULE_SNAPSHOT = "schedule.snapshot"

    # Unknown / unrecognized
    UNKNOWN = "unknown"


class Event(Z4JModel):
    """A single lifecycle event observed by an agent.

    Attributes:
        id: Opaque UUID. Generated by ``uuidv7()`` in Postgres 18+ for
            time-ordering.
        project_id: Project this event belongs to.
        agent_id: Agent that reported the event.
        engine: Engine adapter that produced the event
                (``celery``, ``rq``, ...).
        task_id: Engine-native task ID this event is about.
                 For non-task events (e.g. ``worker.online``), this
                 holds a best-effort identifier or empty string.
        kind: Taxonomy tag - see :class:`EventKind`.
        occurred_at: When the event happened in the source engine.
                     Not the time the brain received it.
        data: Redacted event payload. Shape depends on ``kind``.
              Already run through the redaction engine by the agent
              before transmission. Re-scrubbed by the brain on ingest
              as defense in depth.
    """

    id: UUID
    project_id: UUID
    agent_id: UUID
    engine: str = Field(min_length=1, max_length=40)
    task_id: str = Field(default="", max_length=200)
    kind: EventKind
    occurred_at: datetime
    data: dict[str, Any] = Field(default_factory=dict)


__all__ = ["Event", "EventKind"]
